Service:
  RegionId: cn-hangzhou
  DeployType: ros
  OperationMetadata:
    StatusOperationConfigs:
      - TemplateName: '单机版'
        SupportOperations:
          - Start
          - Stop
          - Restart
    SupportBackup: true
  DeployMetadata:
    SupplierDeployMetadata:
      FileArtifactRelation:
        '{{ computenest::file::JJGGu_nocobase-docker-compose }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
    TemplateConfigs:
      - Name: 单机版
        Url: 'ros_templates/template.yaml'
        AllowedRegions:
          - cn-hangzhou
          - cn-shanghai
          - cn-beijing
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: docker compose deploy
    Image: 'resources/icons/service_logo.png'
Artifact:
  Artifact_1:
    ArtifactType: File
    ArtifactName: JJGGu_nocobase-docker-compose
    ArtifactProperty:
      RegionId: cn-hangzhou
      Url: 'resources/artifact_resources/docker_compose.tar'
  Artifact_2:
    ArtifactType: AcrImage
    ArtifactName: AcrImage-verdaccio-verdaccio
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_1.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_1.Tag}
      RepoType: Public
  Artifact_3:
    ArtifactType: AcrImage
    ArtifactName: AcrImage-mysql
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_2.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_2.Tag}
      RepoType: Public
  Artifact_4:
    ArtifactType: AcrImage
    ArtifactName: AcrImage-postgres
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_3.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_3.Tag}
      RepoType: Public
  Artifact_5:
    ArtifactType: AcrImage
    ArtifactName: AcrImage-nocobase-adminer
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_4.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_4.Tag}
      RepoType: Public
  Artifact_6:
    ArtifactType: AcrImage
    ArtifactName: AcrImage-node
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_5.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_5.Tag}
      RepoType: Public
AcrImageBuilder:
  AcrImage_1:
    BuildType: DockerRepo
    DockerRepoUrl: verdaccio/verdaccio
    RepoName: verdaccio/verdaccio
    Tag: latest
  AcrImage_2:
    BuildType: DockerRepo
    DockerRepoUrl: mysql:8
    RepoName: mysql
    Tag: 8
  AcrImage_3:
    BuildType: DockerRepo
    DockerRepoUrl: postgres:latest
    RepoName: postgres
    Tag: latest
  AcrImage_4:
    BuildType: DockerRepo
    DockerRepoUrl: nocobase/adminer
    RepoName: nocobase/adminer
    Tag: latest
  AcrImage_5:
    BuildType: DockerRepo
    DockerRepoUrl: node:16-stretch-slim
    RepoName: node
    Tag: 16-stretch-slim